### ISSUE TITLE
Reminiscense as Subdomain with Nginx reverse proxy

### ISSUE THREAD

**Issue by vinanrra** [kanishka-linux/reminiscence#35]
Hi,

Thanks for this amazing project, but i would like to do a reverse proxy to a subdomain like this:

reminiscense.domian.xx

But i am a not very familiar with reverse proxy could anyone help me to do it or give me some info to do it myself?

Im using this docker container to do all my reverse proxy:

https://hub.docker.com/r/linuxserver/letsencrypt/

With this:

https://github.com/linuxserver/reverse-proxy-confs

And if possible i will pull the config to the repository.

Thanks.

**Comment by kanishka-linux** [comment]
I think it is possible. Just search internet, you'll get the answer. If you want to serve reminiscence under subdirectory then there is this [issue](https://github.com/kanishka-linux/reminiscence/issues/14) which you can refer to.

**Comment by AndreSouzaAbreu** [comment]
Hello! Thanks for the amazing project!

I'm facing the same problem. I'm trying to run reminiscence under `articles.mydomain.example` but can't get it to work. 

Here is what I've been tried:

The  `docker-compose.yml` file

```
version: '3'

services:
  reminiscence:
    build: .
    command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; python manage.py migrate; python manage.py createdefaultsu; python manage.py collectstatic --no-input; if [ ! -d '/usr/src/reminiscence/static/nltk_data' ]; then echo 'wait..downloading..nltk_data'; python manage.py nltkdownload; fi; gunicorn --max-requests 1000 --worker-class gthread --workers 4 --thread 10 --timeout 300 --bind 0.0.0.0:8000 reminiscence.wsgi"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ./static:/usr/src/reminiscence/static/
      - ./archive:/usr/src/reminiscence/archive/
      - ./logs:/usr/src/reminiscence/logs/
    depends_on:
      - reminiscence-db

  reminiscence-db:
    image: postgres:11
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/postgresql/data/

networks:
   default:
     external:
       name: ${NETWORK}
```
The `.env` file
```
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=verystrongpassword
DOMAIN=articles.mydomain.example
VIRTUAL_PORT=8000
LETSENCRYPT_EMAIL=admin@mydomain.example
NETWORK=webproxy
```

I deleted the `nginx` service in the original `Dockerfile`  . Instead, I'm using this [nginx proxy](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion).

Any help is welcome!
